### ISSUE TITLE
Add configuration options (after setting up for the first time)

### ISSUE THREAD

**Issue by geoklar** [ThessalonikiNet-MeetUp/NoiseDetectionClient#1]
As a user I should be able to reconfigure my decibel level and Id.

**Comment by ktasos** [comment]
@geoklar thanks for the feedback :) I have updated the client's UI and the user can set both Device ID and Device Level (see commit https://github.com/ThessalonikiNet-MeetUp/NoiseDetectionClient/commit/498e4a9f429558d0682994494b3e187a5db7d197)
